# Uncomment this line to define a global platform for your project
 platform :ios, '8.1'

target 'needleAgent' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!
  # Pods for needleAgent
  pod 'CocoaAsyncSocket'

end
